#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DOS")]
	public partial class DBConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBConnectionDataContext() : 
				base(global::DOSService.Properties.Settings.Default.DOSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_getAppConfig")]
		public ISingleResult<usp_getAppConfigResult> usp_getAppConfig()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_getAppConfigResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_getAllEmail")]
		public ISingleResult<usp_getAllEmailResult> usp_getAllEmail()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_getAllEmailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_insertlogging")]
		public ISingleResult<usp_insertloggingResult> usp_insertlogging([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="Char(1)")] System.Nullable<char> type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ActionBy", DbType="VarChar(50)")] string actionBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProgramReference", DbType="VarChar(100)")] string programReference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(2000)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DebugLevel", DbType="Int")] System.Nullable<int> debugLevel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReferenceType", DbType="VarChar(100)")] string referenceType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reference", DbType="VarChar(100)")] string reference, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Updates", DbType="Xml")] System.Xml.Linq.XElement updates)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), type, actionBy, programReference, description, debugLevel, referenceType, reference, updates);
			return ((ISingleResult<usp_insertloggingResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_getAllCourseReminderRecipients")]
		public ISingleResult<usp_getAllCourseReminderRecipientsResult> usp_getAllCourseReminderRecipients()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_getAllCourseReminderRecipientsResult>)(result.ReturnValue));
		}
	}
	
	public partial class usp_getAppConfigResult
	{
		
		private string _ConfigName;
		
		private string _value;
		
		public usp_getAppConfigResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfigName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ConfigName
		{
			get
			{
				return this._ConfigName;
			}
			set
			{
				if ((this._ConfigName != value))
				{
					this._ConfigName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this._value = value;
				}
			}
		}
	}
	
	public partial class usp_getAllEmailResult
	{
		
		private string _EmailType;
		
		private string _EmailContent;
		
		public usp_getAllEmailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailType", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EmailType
		{
			get
			{
				return this._EmailType;
			}
			set
			{
				if ((this._EmailType != value))
				{
					this._EmailType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailContent", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string EmailContent
		{
			get
			{
				return this._EmailContent;
			}
			set
			{
				if ((this._EmailContent != value))
				{
					this._EmailContent = value;
				}
			}
		}
	}
	
	public partial class usp_insertloggingResult
	{
		
		private System.Nullable<decimal> _Result;
		
		public usp_insertloggingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class usp_getAllCourseReminderRecipientsResult
	{
		
		private string _Email;
		
		private string _Name;
		
		private string _CourseName;
		
		private string _AreaName;
		
		private System.TimeSpan _CourseStartTime;
		
		private System.TimeSpan _CourseEndTime;
		
		private string _CourseStartDate;
		
		public usp_getAllCourseReminderRecipientsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CourseName
		{
			get
			{
				return this._CourseName;
			}
			set
			{
				if ((this._CourseName != value))
				{
					this._CourseName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaName", DbType="VarChar(100)")]
		public string AreaName
		{
			get
			{
				return this._AreaName;
			}
			set
			{
				if ((this._AreaName != value))
				{
					this._AreaName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseStartTime", DbType="Time NOT NULL")]
		public System.TimeSpan CourseStartTime
		{
			get
			{
				return this._CourseStartTime;
			}
			set
			{
				if ((this._CourseStartTime != value))
				{
					this._CourseStartTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseEndTime", DbType="Time NOT NULL")]
		public System.TimeSpan CourseEndTime
		{
			get
			{
				return this._CourseEndTime;
			}
			set
			{
				if ((this._CourseEndTime != value))
				{
					this._CourseEndTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseStartDate", DbType="VarChar(8000) NOT NULL", CanBeNull=false)]
		public string CourseStartDate
		{
			get
			{
				return this._CourseStartDate;
			}
			set
			{
				if ((this._CourseStartDate != value))
				{
					this._CourseStartDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
